"""Shared logic for the Phase H regression harness.

Both ``tests/test_regression_render_smoke.py`` and
``scripts/regenerate_regression_fixtures.py`` import from this module
so the "compute expected outputs from an input fixture" path is a
single source of truth — diverge those and the regenerator silently
produces fixtures the test rejects.

Underscore prefix keeps pytest from auto-collecting it as a test module.

Fixture layout — one pair per case:

    tests/fixtures/regression/{family}/case_{N}.input.yaml
    tests/fixtures/regression/{family}/case_{N}.expected.yaml

The ``.input.yaml`` is hand-authored and version-controlled; the
``.expected.yaml`` is generated by ``regenerate_regression_fixtures.py``
and reviewed via ``git diff`` before commit. When intentional drift
lands in Phase A–G config (e.g. a family's quality_suffix changes),
re-run the regenerator, eyeball the diff, commit both.

Input shape (all keys optional unless noted):

    description: str               # human-readable case label
    family: str                    # required — one of the 6 families
    content_level: str             # required — T1_..T4_ tier
    audience: str | null           # "deviantart"|"patreon"|null
    character:
      base_prompt: str             # required (composer needs this)
      negative_prompt: str
    scene:                         # required — at least one field
      pose: str
      camera: str
      camera_angle: str
      lighting: str
      environment_detail: str
      mood_note: str
      expression: str
      composition_intent: str      # close-up|medium|full-body|wide
      booru_tags: str              # pony / illustrious primary
      scene_prose: str             # flux / chroma / illustrious / flux2 primary
      camera_spec: str             # sdxl primary
      clothing: str                # sdxl primary
      source_tag: str              # pony only
    style_profile:
      base_style_keywords: str
      base_negative_prompt: str
    trigger_words: [str, ...]      # passed through verbatim

Expected shape (regenerator writes, test asserts):

    prompt_text: str
    prompt_token_count: int
    negative_prompt: str
    ratio: str                     # one of the 4 RATIO_TO_RESOLUTION keys
    resolution: [int, int]
    reason: str                    # ratio-pick reason (debugging)
"""

from __future__ import annotations

import os
import random
from pathlib import Path
from typing import Any

import yaml

from src.core.ratio_selector import RatioSelector
from src.memory.family_loader import FamilyLoader
from src.prompt.builder import PromptBuilder
from src.prompt.tokenizer import count_tokens

# Repo paths — independent of the caller's CWD so the test and the
# regenerator both work no matter how they're invoked.
REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_ROOT = REPO_ROOT / "tests" / "fixtures" / "regression"
PIPELINE_YAML = REPO_ROOT / "config" / "pipeline.yaml"
RATIO_SIGNALS_YAML = REPO_ROOT / "config" / "ratio_signals.yaml"


# ── singletons ──────────────────────────────────────────────────────


def _load_pipeline_cfg() -> dict[str, Any]:
    with open(PIPELINE_YAML) as f:
        return yaml.safe_load(f)


def make_ratio_selector() -> RatioSelector:
    """Build the same selector the engine builds at runtime."""
    return RatioSelector.from_config(
        _load_pipeline_cfg(),
        ratio_signals_path=RATIO_SIGNALS_YAML,
    )


def make_family_loader() -> FamilyLoader:
    return FamilyLoader()


# ── fixture I/O ─────────────────────────────────────────────────────


def discover_input_fixtures() -> list[Path]:
    """Return every ``case_*.input.yaml`` under ``FIXTURE_ROOT``, sorted."""
    return sorted(FIXTURE_ROOT.glob("*/case_*.input.yaml"))


def expected_path_for(input_path: Path) -> Path:
    return input_path.with_name(input_path.name.replace(".input.yaml", ".expected.yaml"))


def load_yaml(path: Path) -> dict[str, Any]:
    with open(path) as f:
        return yaml.safe_load(f) or {}


def dump_yaml(path: Path, data: dict[str, Any]) -> None:
    """Write YAML with stable key ordering for diff readability."""
    with open(path, "w") as f:
        yaml.safe_dump(
            data,
            f,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
            width=100,
        )


# ── core: compute expected outputs from one input fixture ───────────


def compute_expected(input_data: dict[str, Any]) -> dict[str, Any]:
    """Run the real builder + selector + tokenizer on one fixture.

    Returns the dict to write under ``expected:``. No I/O beyond
    YAML config reads (which are cached).
    """
    family_id = input_data["family"]
    content_level = input_data["content_level"]
    audience = input_data.get("audience")

    family = make_family_loader().get_family(family_id)
    builder = PromptBuilder()
    selector = make_ratio_selector()

    character = input_data.get("character") or {}
    scene = input_data.get("scene") or {}
    style_profile = input_data.get("style_profile") or {}
    trigger_words = input_data.get("trigger_words") or []

    built = builder.build_one(
        character=character,
        scene=scene,
        style_profile=style_profile,
        family=family,
        trigger_words=trigger_words,
    )

    # Deterministic ratio pick — passes audience and family_id through
    # so the family-quality and audience bonuses fire when configured.
    pick = selector.select(
        scene=scene,
        content_level=content_level,
        family_id=family_id,
        audience=audience,
        rng=random.Random(0),  # belt-and-braces; the selector's hash
                               # seed is already deterministic, but a
                               # zero-seeded RNG removes any doubt
                               # across Python releases.
    )

    return {
        "prompt_text": built["prompt_text"],
        "prompt_token_count": count_tokens(
            built["prompt_text"], family.tokenizer_id,
        ),
        "negative_prompt": built["negative_prompt"],
        "ratio": pick.ratio,
        "resolution": list(pick.resolution),
        "reason": pick.reason,
    }


# ── pretty-print path used in test failure messages ─────────────────


def relpath(path: Path) -> str:
    """Repo-relative path for cleaner pytest IDs / error messages."""
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)
